### ISSUE TITLE
some Doubts about a symbol

### ISSUE THREAD

**Issue by oujieww** [mingkaid/rl-prompt#10]
verbalizers = ['\u0120terrible', '\u0120great'] 

why need to add \u0120 ？

**Comment by mingkaid** [comment]
Thank you for reaching out. \u0120 ("Ġ") is [the character for "space"](https://github.com/openai/gpt-2/issues/80) in the BPE tokenizer, which is used by both GPT-2 and RoBERTa that we use for our work. 

For example, the sentence "This is great" will be tokenized as `['This', 'Ġis', 'Ġgreat']`. Indeed, we use the tokens with space because this is how the words "terrible" and "great" typically appear in sentences. 

Other tokenizers also use special characters to represent spaces, e.g., WordPiece (BERT) uses "#" and SentencePiece (T-5) uses "▁" (see [this issue](https://github.com/huggingface/transformers/issues/5087) for discussion). 

I hope this answers your question, and feel free to follow up if you have more. I'm closing this issue now because it's a clarification question.

**Comment by oujieww** [comment]
Thank you for your patient reply.
