### ISSUE TITLE
generate_prompts.py may be only usable for `input_specific=True` option?

### ISSUE THREAD

**Issue by Dinxin** [mingkaid/rl-prompt#3]
![image](https://user-images.githubusercontent.com/19572535/183356014-a1b10702-1a46-44df-b262-591975d63f0d.png)

model._model will have `_tst_inputs` attribute only if the option `input_specific` is True.

**Comment by mingkaid** [comment]
Thank you for your interest! The `model._model` is used for generating the prompt, so we only load the input if `input_specific` is True, which indicates that we want to condition the prompt on the input. 

If I understand it correctly, this screenshot is from one of the evaluation scripts for text style transfer. As described in our paper, we experiment with input-specific prompts for this task, so the evaluation script assumes that `input_specific` is True. 

I hope this answers your question. I'm closing this for now because it's a clarification question. If you have any other specific questions for your use case, please feel free to create another issue to describe it in more detail
