### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by rabi-fei** [mingkaid/rl-prompt#32]
Hi, This repo is wonderful and helpful for my research. But I am struggling to reproduce the result.  When I run download_tst_classifiers.py, the error happened. I am wondering if the link has problems.
<Failed to establish a new connection: [Errno 101] Network is unreachable>

Also, can you give me some suggestions on how to construct a pipeline to apply RLprompt to the generation task? text-style-transfer is quite complex for me. Thanks :-).

**Comment by mingkaid** [comment]
Thank you for your interest! 

1. **Classifier Download**: May I ask if you can access Google Drive? That is where our model files are hosted. If you do not, let us know and we can set up an endpoint available to you. 
2. **Generation Task**: Please refer to our script [run_tst.py](https://github.com/mingkaid/rl-prompt/blob/main/examples/text-style-transfer/run_tst.py) for an example of the pipeline. To apply to your own task, you can simply create your own reward module. That is, simply swap out [this line](https://github.com/mingkaid/rl-prompt/blob/main/examples/text-style-transfer/run_tst.py#L42) for your own implemented task. 

Let us know if you have other questions. I am closing this issue now because it's a clarification question.
