### ISSUE TITLE
The data in 'data/prompt-gpt2-vocab' folder seems meaningless?

### ISSUE THREAD

**Issue by Dinxin** [mingkaid/rl-prompt#4]
train.source.positive: there is only "LABEL_1".
<img width="694" alt="WeChatWorkScreenshot_9bcd7291-95b1-43f1-9495-2c094d0b5925" src="https://user-images.githubusercontent.com/19572535/183357202-4918c510-5954-45f5-96d0-2250c9809b82.png">
train.target.negative: there are only repeating "issues"s. I don't think it is a meaningful input.
<img width="546" alt="WeChatWorkScreenshot_ed0c285e-6a9e-45a6-829a-39d5feaa28b5" src="https://user-images.githubusercontent.com/19572535/183357371-fcbe72b8-6b2e-4e03-af22-10ff460d9897.png">

Could you please provide the instructions on the meaning of these files?

**Comment by mingkaid** [comment]
Thank you for your interest! These are placeholders for the prompt generator, and will be removed in future updates.

Specifically, the "LABEL_1" in `train.source.positive` is only used for text style transfer. "LABEL_1" refers to the target style label, which means positive sentiment for Yelp, and modern English for Shakespeare. In `train.source.negative`, you will see `LABEL_0`, which serves the same purpose. 

The repeating "issues"'s in `train.target.negative` is likewise just a placeholder for generating prompts with 5 tokens.

I hope this answers your question. I'm closing this now because it's a clarification question. If you have any specific questions about your use case, please feel free to create another issue with the details, so we can assist
