### ISSUE TITLE
Could not find the exact place where the training set is input?

### ISSUE THREAD

**Issue by Dinxin** [mingkaid/rl-prompt#5]
This repo seems to only provide the prompt dataset in `data` folder, ignoring the needed training set (Yelp).
I cannot reproduce the experimental results demonstrated in the paper. 
Could you please provide the full data and program which are necessary for the result reproduction?

**Comment by mingkaid** [comment]
Thanks for telling us about your issue, and I apologize for your experience. 

The training data is in the `prompt_tasks` folder. For text style transfer, we use the `preprocessed` data which follows the tokenization format of GPT-2.

We will clean up the code further in the next update. I’m closing this now because it’s a clarification question

**Comment by Dinxin** [comment]
It seems that no programs read data from the `prompt_tasks` folder.

**Comment by mingkaid** [comment]
The file `sql/rewards.py` reads the data. You are also welcome to check out our restructured code (still WIP), which is located at the `modular-interface` branch

**Comment by Dinxin** [comment]
Many thanks. I check the restructured `modular-interface` branch.
